version: '{branch}.{build}'
environment:
  RunOctoPack: truepull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore Source\AuthenticationServer.sln
build:
  #publish_nuget: true
  #publish_nuget_symbols: true
  #include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: nuget pack "$(APPVEYOR_BUILD_FOLDER)\Source\AuthenticationServer.Claims\AuthenticationServer.Claims.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -IncludeReferencedProjects
configuration: Release
deploy:
- provider: NuGet
  artifact: Affecto.AuthenticationServer.Claims.nupkg
  api_key:
    secure: ySttUuKXaqz/qn7dZRtJJs7H8wTDgT8Wgi55QFGZjmVE2XL14T2puaPiBcNMZC1l
  on:
    appveyor_repo_tag: true